NAME = colle-2

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) ft_colle_2.c rush00.c rush01.c rush02.c rush03.c rush04.c ft_putchar.c ft_putnbr.c ft_strcat.c ft_strcpy.c ft_strcmp.c ft_strncat.c ft_putstr.c
clean:
	/bin/rm -f $(NAME)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all